# Generated by Django 4.1.7 on 2023-03-16 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_app', '0009_article_number_article_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kk', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(help_text='Please upload only image!', max_length=255, null=True, upload_to='files/journal_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('file_pdf', models.FileField(blank=True, help_text='Please upload only .pdf!', max_length=255, null=True, upload_to=journal.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="To'liq versiyasi")),
                ('file_head_pdf', models.FileField(blank=True, help_text='Please upload only .pdf!', max_length=255, null=True, upload_to='files/journals/head_template', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Jurnalni bosh qismi')),
                ('file_mundarija', models.FileField(max_length=255, null=True, upload_to='files/journals/mundarija', verbose_name='Mundarija')),
                ('count_of_head_file', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('is_split', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='JournalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=journal.models.upload_to_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveBigIntegerField(default=0)),
                ('end_page', models.PositiveBigIntegerField(default=0)),
                ('order_page', models.IntegerField(default=0)),
                ('article_pdf', models.FileField(help_text='Please upload only .pdf!', max_length=255, null=True, upload_to='files/split_article', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fayl')),
                ('year', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article_app.article')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_article', to='journal.journal')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journalnumber'),
        ),
        migrations.AddField(
            model_name='journal',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journalyear'),
        ),
    ]
