# Generated by Django 4.2.1 on 2023-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalarticle',
            name='count_author',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
