# Generated by Django 4.2.1 on 2023-10-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalarticle_count_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='name_kk',
        ),
    ]
