# Generated by Django 4.2.1 on 2023-12-18 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journal_name_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalyear',
            name='year_img',
            field=models.ImageField(blank=True, help_text='Please upload only image!', null=True, upload_to='image_year/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
