# Generated by Django 4.2.27 on 2026-01-01 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalyear_year_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.journalnumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='journal.journalyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalnumber',
            name='number',
            field=models.PositiveBigIntegerField(default=1, help_text="Jurnal soni (1 dan 10 gacha) bo'lishi kerak.", unique=True, validators=[django.core.validators.MinValueValidator(1, message="Son 1 dan kichik bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(10, message="Son 10 dan katta bo'lishi mumkin emas.")]),
        ),
        migrations.AlterField(
            model_name='journalyear',
            name='year',
            field=models.PositiveBigIntegerField(default=2000, help_text="Jurnal sonining yili (1995 dan 2100 gacha) bo'lishi kerak.", unique=True, validators=[django.core.validators.MinValueValidator(1995, message="Son 1995 dan kichik bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(2100, message="Son 2100 dan katta bo'lishi mumkin emas.")]),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('year', 'number'), name='unique_journal_year_number'),
        ),
    ]
