# Generated by Django 4.1.4 on 2023-02-07 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('template_file', models.FileField(blank=True, help_text='Please upload only .doc or .docx files!', max_length=255, upload_to='files/template/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])])),
                ('code_name', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
