# Generated by Django 4.2.1 on 2023-07-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_maker', '0001_initial'),
        ('expert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='lang_test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest'),
        ),
        migrations.AddField(
            model_name='expert',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficultynational'),
        ),
        migrations.AddField(
            model_name='expert',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_subject', to='test_maker.subject'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.expert'),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.status'),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='status_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.checktestexpertstatus'),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.steptest'),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='submission_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.submissiontest'),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkedtestcount',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.expert'),
        ),
        migrations.AddField(
            model_name='checkedtestcount',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject'),
        ),
    ]
