# Generated by Django 4.2.1 on 2023-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktestexpert',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
