# Generated by Django 4.2.1 on 2023-12-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_checktestexpert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktestexpert',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.expert'),
        ),
    ]
