# Generated by Django 4.2.1 on 2023-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_alter_checktestexpert_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktestexpert',
            name='is_job_given',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='job_given_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
