# Generated by Django 4.2.1 on 2023-12-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_checktestexpert_is_job_given_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobControlSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.SmallIntegerField(default=-1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('control_sheet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.controlsheet')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.checktestexpert')),
            ],
        ),
    ]
