# Generated by Django 4.2.1 on 2023-12-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_controlsheet_jobcontrolsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='is_third_expert',
            field=models.BooleanField(default=False),
        ),
    ]
