# Generated by Django 4.2.1 on 2024-01-24 13:02

from django.db import migrations, models
import django.db.models.deletion
import expert.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0007_submissiontest_step'),
        ('moderator', '0003_moderator_upload_type_moderatorchecktest_is_check_and_more'),
        ('expert', '0007_expert_is_third_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedtestcount',
            name='confirmed_count',
        ),
        migrations.RemoveField(
            model_name='checkedtestcount',
            name='denied_count',
        ),
        migrations.RemoveField(
            model_name='checkedtestcount',
            name='incoming_count',
        ),
        migrations.RemoveField(
            model_name='checkedtestcount',
            name='progress_count',
        ),
        migrations.AddField(
            model_name='checkedtestcount',
            name='job_all_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='is_third_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checktestexpert',
            name='job_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='controlsheet',
            name='expertise_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expert',
            name='certificate_assessment',
            field=models.ImageField(blank=True, null=True, upload_to=expert.models.image_dir_path),
        ),
        migrations.AddField(
            model_name='expert',
            name='certificate_training',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='is_lang_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcontrolsheet',
            name='expertise_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.PositiveSmallIntegerField(default=0)),
                ('expertise_type', models.PositiveSmallIntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.part')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseQuestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.SmallIntegerField(default=-1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expertise_type', models.PositiveSmallIntegerField(default=0)),
                ('control_sheet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.controlsheet')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.moderatorchecktest')),
            ],
        ),
        migrations.AddField(
            model_name='controlsheet',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.sheet'),
        ),
    ]
