# Generated by Django 4.2.1 on 2024-01-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0009_typetestupload_status'),
        ('expert', '0008_remove_checkedtestcount_confirmed_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSheetNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlsheet',
            name='expertise_type',
        ),
        migrations.RemoveField(
            model_name='expertisequestionjob',
            name='expertise_type',
        ),
        migrations.RemoveField(
            model_name='jobcontrolsheet',
            name='expertise_type',
        ),
        migrations.CreateModel(
            name='SheetNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.leveldifficultynational')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.part')),
            ],
        ),
        migrations.CreateModel(
            name='JobControlSheetNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.SmallIntegerField(default=-1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('control_sheet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.controlsheetns')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.checktestexpert')),
            ],
        ),
        migrations.AddField(
            model_name='controlsheetns',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.sheetns'),
        ),
        migrations.AlterField(
            model_name='expertisequestionjob',
            name='control_sheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.controlsheetns'),
        ),
    ]
