# Generated by Django 4.2.1 on 2024-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_controlsheetns_remove_controlsheet_expertise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsheetns',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
