# Generated by Django 4.2.1 on 2024-02-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0009_typetestupload_status'),
        ('expert', '0010_controlsheetns_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsheetns',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.subject'),
        ),
    ]
