# Generated by Django 4.2.1 on 2024-02-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0010_leveldifficultynational_status_optionpart_and_more'),
        ('expert', '0011_controlsheetns_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsheetns',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlsheetns',
            name='part_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.optionpart'),
        ),
    ]
