# Generated by Django 4.2.1 on 2024-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_controlsheetns_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expert',
            name='is_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expert',
            name='is_sender',
            field=models.BooleanField(default=False),
        ),
    ]
