# Generated by Django 4.1.4 on 2022-12-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blankpage_updated_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankpage',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
