# Generated by Django 4.2.1 on 2023-10-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_blankpage_body_en_blankpage_body_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blankpage',
            name='body_kk',
        ),
        migrations.RemoveField(
            model_name='blankpage',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='desc_kk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_kk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_kk',
        ),
    ]
