# Generated by Django 4.2.1 on 2023-07-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_maker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('key', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('file_word', models.FileField(blank=True, null=True, upload_to='')),
                ('file_audio', models.FileField(blank=True, null=True, upload_to='')),
                ('is_have_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficultynational')),
                ('part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.part')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.status')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('submission_test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.submissiontest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('tex_code', models.TextField(blank=True)),
                ('a', models.TextField(blank=True)),
                ('b', models.TextField(blank=True)),
                ('c', models.TextField(blank=True)),
                ('d', models.TextField(blank=True)),
                ('tex_file', models.FileField(blank=True, null=True, upload_to='')),
                ('question_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('option_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficulty')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='question.status')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('submission_test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.submissiontest')),
                ('theme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.theme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
