# Generated by Django 4.2.1 on 2024-01-30 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_maker', '0009_typetestupload_status'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('file_word', models.FileField(blank=True, null=True, upload_to='')),
                ('file_audio', models.FileField(blank=True, null=True, upload_to='')),
                ('is_have_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficultynational')),
                ('part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.part')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('submission_test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.submissiontest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
