# Generated by Django 4.2.1 on 2024-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_mockquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockquestion',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnational',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
