# Generated by Django 4.2.1 on 2024-03-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0012_testconfirmationcount_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_mockquestion_is_edit_questionnational_is_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='part_option',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='test_maker.optionpart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnational',
            name='part_option',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='test_maker.optionpart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnational',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DownloadExcellLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.paymenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
