# Generated by Django 4.2.1 on 2023-10-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
        ('test_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.DurationField(default='00:30:00'),
        ),
        migrations.AddField(
            model_name='subject',
            name='limit_question',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='picture',
            field=models.ImageField(default='no-image.png', upload_to='subjects/'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_for_pupil', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_maker.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField(default=0)),
                ('count_question', models.PositiveIntegerField(default=0)),
                ('limit_question', models.PositiveSmallIntegerField(default=5)),
                ('questions', models.ManyToManyField(blank=True, related_name='questions', to='question.questionadmission')),
                ('subject_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_maker.subjectbox')),
            ],
        ),
    ]
