# Generated by Django 4.2.1 on 2023-11-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0002_subject_duration_subject_limit_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
            ],
        ),
        migrations.AlterModelOptions(
            name='typetestupload',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='subject',
        ),
        migrations.AddField(
            model_name='theme',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.section'),
        ),
    ]
