# Generated by Django 4.2.1 on 2023-11-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0003_chapter_alter_typetestupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.chapter'),
        ),
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.section'),
        ),
    ]
