# Generated by Django 4.2.1 on 2024-01-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0004_submission_chapter_submission_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='subject',
        ),
        migrations.AddField(
            model_name='part',
            name='is_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissiontest',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissiontest',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.state'),
        ),
    ]
