# Generated by Django 4.2.1 on 2024-01-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0005_state_remove_part_subject_part_is_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontest',
            name='step',
        ),
    ]
