# Generated by Django 4.2.1 on 2024-01-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0006_remove_submissiontest_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontest',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.state'),
        ),
    ]
