# Generated by Django 4.2.1 on 2024-01-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0008_testconfirmationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetestupload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
