# Generated by Django 4.2.1 on 2024-02-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0009_typetestupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldifficultynational',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OptionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficultynational')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.part')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('type_test_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.typetestupload')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='part_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.optionpart'),
        ),
    ]
