# Generated by Django 4.2.1 on 2024-02-24 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0010_leveldifficultynational_status_optionpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='topic_n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='question_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc'])])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('lang_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.languagetest')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.leveldifficultynational')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.part')),
                ('part_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.optionpart')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject')),
                ('type_test_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.typetestupload')),
            ],
        ),
    ]
