# Generated by Django 4.2.1 on 2024-03-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0011_submission_topic_n_templatequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconfirmationcount',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.leveldifficultynational'),
        ),
        migrations.AddField(
            model_name='testconfirmationcount',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.optionpart'),
        ),
        migrations.AddField(
            model_name='testconfirmationcount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.part'),
        ),
        migrations.AddField(
            model_name='testconfirmationcount',
            name='subject_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.languagetest'),
        ),
    ]
