# Generated by Django 4.2.1 on 2024-03-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0012_testconfirmationcount_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpart',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='optionpart',
            name='number_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='number_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testconfirmationcount',
            name='db_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='testconfirmationcount',
            name='template_q',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.templatequestion'),
        ),
    ]
