# Generated by Django 4.2.1 on 2024-04-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0013_optionpart_key_optionpart_number_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testconfirmationcount',
            name='db_type',
        ),
    ]
