# Generated by Django 4.2.13 on 2024-09-26 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0014_remove_testconfirmationcount_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file_word',
            field=models.FileField(blank=True, max_length=255, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
    ]
