# Generated by Django 4.1.4 on 2022-12-20 13:22

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_app.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Username')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Surname')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('avatar', models.ImageField(blank=True, default='user.png', null=True, upload_to='avatars/%Y/%m/%d', validators=[user_app.validator.validate_file_size, django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Avatar')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone number')),
                ('pser', models.CharField(blank=True, max_length=2, null=True, verbose_name='Passport ')),
                ('pnum', models.CharField(blank=True, max_length=7, null=True, verbose_name='Passport ')),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=10, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=10, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=10, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=10, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerEditorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('code_name', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_kk', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Please upload only .doc, .docx or .pdf files!', max_length=255, null=True, upload_to='files/reviewer/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Fayl')),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.editor')),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.reviewer')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.reviewereditorstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('result', models.PositiveSmallIntegerField(default=0)),
                ('is_extra', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_article', to='article_app.article')),
                ('editor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_editor', to='user_app.editor')),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to='user_app.reviewer')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_status', to='user_app.statusreview')),
            ],
        ),
        migrations.AddField(
            model_name='reviewer',
            name='scientific_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.scientificdegree'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='reviewer_sections', to='article_app.section'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='allowed_role_menus', to='user_app.role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_roles', to='user_app.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
