# Generated by Django 4.1.4 on 2023-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
