# Generated by Django 4.1.4 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_editor_is_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clicked_template',
            field=models.BooleanField(default=False),
        ),
    ]
