# Generated by Django 4.1.4 on 2023-02-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_is_clicked_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_clicked_template',
        ),
    ]
