# Generated by Django 4.1.7 on 2023-03-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0009_article_number_article_year'),
        ('user_app', '0004_remove_user_is_clicked_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerarticle',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.notification'),
        ),
        migrations.AlterField(
            model_name='reviewerarticle',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
