# Generated by Django 4.2.1 on 2023-07-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_reviewerarticle_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jshshr',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sc_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.scientificdegree'),
        ),
    ]
