# Generated by Django 4.2.1 on 2023-10-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_jshshr_user_sc_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='scientificdegree',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='statusreview',
            name='name_kk',
        ),
        migrations.AddField(
            model_name='menu',
            name='system_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='doc_give_place_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_role',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jshshr',
            field=models.CharField(blank=True, default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pnum',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pser',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Passport'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.region')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.district'),
        ),
    ]
