# Generated by Django 4.2.1 on 2023-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_country_name_kk_remove_gender_name_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
