# Generated by Django 4.2.13 on 2025-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/reviewer/%Y/%m/%d', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
