# Generated by Django 4.2.13 on 2025-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_reviewerfile_file_alter_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerarticle',
            name='is_resubmit_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
