# Generated by Django 4.1.4 on 2022-12-20 14:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('abstract', ckeditor.fields.RichTextField(blank=True)),
                ('abstract_en', ckeditor.fields.RichTextField(blank=True)),
                ('keywords', ckeditor.fields.RichTextField(blank=True)),
                ('keywords_en', ckeditor.fields.RichTextField(blank=True)),
                ('references', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_resubmit', models.BooleanField(default=False)),
                ('is_publish_journal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filePDF', models.FileField(blank=True, null=True, upload_to='files/articles/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Pdf Fayl')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Please upload only .doc or .docx files!', max_length=255, upload_to='files/articles/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Word Fayl')),
                ('file_status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('name_uz', models.CharField(default=None, max_length=100, null=True)),
                ('name_en', models.CharField(default=None, max_length=100, null=True)),
                ('name_ru', models.CharField(default=None, max_length=100, null=True)),
                ('name_kk', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('message_uz', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('message_ru', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('message_kk', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_update_article', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.article')),
            ],
        ),
    ]
