# Generated by Django 4.1.4 on 2023-01-26 07:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
