# Generated by Django 4.1.4 on 2023-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_alter_article_abstract_alter_article_abstract_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_page',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='order_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='start_page',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
