# Generated by Django 4.1.4 on 2023-03-01 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_article_end_page_article_order_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(blank=True, help_text='Please upload only .doc, .docx or .pdf files!', max_length=255, upload_to='files/articles/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Word, Pdf Fayl'),
        ),
    ]
