# Generated by Django 4.1.7 on 2023-03-11 12:22

import article_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_alter_articlefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filePDF',
            field=models.FileField(blank=True, null=True, upload_to=article_app.models.upload_to_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Pdf Fayl'),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(blank=True, help_text='Please upload only .doc or .docx or files!', max_length=255, upload_to=article_app.models.upload_to_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Word, Pdf Fayl'),
        ),
    ]
