# Generated by Django 4.1.7 on 2023-03-13 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0006_alter_article_filepdf_alter_articlefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='checked_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Pdf Fayl'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_checked_upload_file',
            field=models.BooleanField(default=False),
        ),
    ]
