# Generated by Django 4.1.7 on 2023-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_article_checked_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='references',
        ),
        migrations.AddField(
            model_name='articlelanguage',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='articlelanguage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articlestatus',
            name='key',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articletype',
            name='key',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='key',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='key',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
