# Generated by Django 4.1.7 on 2023-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0008_remove_article_references_articlelanguage_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
