# Generated by Django 4.2.1 on 2023-07-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0009_article_number_article_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_en',
            field=models.TextField(blank=True),
        ),
    ]
