# Generated by Django 4.2.1 on 2023-10-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0010_alter_article_abstract_alter_article_abstract_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelanguage',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='articlestatus',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_kk',
        ),
        migrations.RemoveField(
            model_name='notificationstatus',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name_kk',
        ),
    ]
