from django.urls import path
from test_maker.views import *

urlpatterns = [
    path('upload_test/', upload_test, name='upload_test'),
    path('subject_box/', subject_box, name='subject_box'),
    path('subjects/', get_subjects, name='subjects'),
    path('create_subject/', create_subject, name='create_subject'),
    path('edit_subject/<int:pk>/', edit_subject, name='edit_subject'),
    path('delete_subject/<int:pk>/', delete_subject, name='delete_subject'),
    path('upload_test/<int:pk>/', edit_test, name='edit_test'),
    path('get-topics-by-section/', get_topic_by_section, name='get_topic_by_section'),
    path('get_subject_by_typeid/', get_subject_by_typeid, name='get_subject_by_typeid'),
    path('get-chapter-by-subject/', get_chapter_by_subject, name='get_chapter_by_subject'),
    path('get-section-by-chapter/', get_section_by_chapter, name='get_section_by_chapter'),
    path('get-lang-by-subject/', get_lang_by_subject, name='get_lang_by_subject'),
    path('get-part-by-type/', get_part_by_type, name='get_part_by_type'),
    path('get_is_have_audio/', get_is_have_audio, name='get_is_have_audio'),
    path('resend/', resend, name='resend'),
    path('resend/<int:pk>/', resend_test, name='resend_test'),
    path('my_submit_tests/', my_submit_tests, name='my_submit_tests'),
    path('load_my_submit_tests_in_progress/', load_my_submit_tests_in_progress, name='load_my_submit_tests_in_progress'),
    # path('load_my_submit_tests_denied/', load_my_submit_tests_denied, name='load_my_submit_tests_denied'),
    path('question_box/<int:pk>/', question_box, name='question_box'),
    path('set_cookie/', set_cookie_view, name='set_cookie_page'),
    path('delete_cookie_view/', delete_cookie_view, name='delete_cookie_view'),
    path('incoming_questions_dashboard/', incoming_questions_dashboard, name='incoming_questions_dashboard'),
    path('load_incoming_questions/', load_incoming_questions, name='load_incoming_questions'),
    path('question_info/', view_question, name='view_question_incoming'),
    path('question_info/<int:pk>/', question_info, name='question_info'),
    path('get_work/', get_work, name='get_work'),
    path('get_level_dn_list/', get_level_dn_list, name='get_level_dn_list'),
    path('get_part_option/', get_part_option, name='get_part_option'),
    path('get_template_part_option/', get_template_part_option, name='get_template_part_option'),
    path('get_rejected_jobcontrol/', get_rejected_jobcontrol, name='get_rejected_jobcontrol'),
    path('get_rejected_jobcontrol/<int:pk>/', get_rejected_jobcontrol_sheets, name='get_rejected_jobcontrol_sheets'),
]
