# Generated by Django 4.2.1 on 2024-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyconvertedtexttospeech',
            name='audio_file',
            field=models.FilePathField(path='speech/'),
        ),
    ]
