# Generated by Django 4.2.1 on 2024-01-24 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_alter_historyconvertedtexttospeech_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyconvertedtexttospeech',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
