# Generated by Django 4.2.1 on 2024-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_textlanguage_generatedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtext',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedtext',
            name='test_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
