# Generated by Django 4.2.1 on 2024-01-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converttexcount',
            name='new_count',
        ),
        migrations.RemoveField(
            model_name='converttexcount',
            name='progress_count',
        ),
        migrations.RemoveField(
            model_name='converttexcount',
            name='subject',
        ),
        migrations.AddField(
            model_name='moderatorchecktest',
            name='is_job_given',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moderatorchecktest',
            name='job_finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderatorchecktest',
            name='job_given_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='converttexcount',
            name='converted_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
