# Generated by Django 4.2.1 on 2024-01-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0007_submissiontest_step'),
        ('moderator', '0002_remove_converttexcount_new_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='upload_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='test_maker.typetestupload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatorchecktest',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorchecktest',
            name='upload_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='test_maker.typetestupload'),
            preserve_default=False,
        ),
    ]
