# Generated by Django 4.2.1 on 2024-01-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0007_submissiontest_step'),
        ('moderator', '0003_moderator_upload_type_moderatorchecktest_is_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.languagetest'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.subject'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='upload_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.typetestupload'),
        ),
    ]
