# Generated by Django 4.2.1 on 2024-01-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0009_typetestupload_status'),
        ('moderator', '0004_moderator_language_moderator_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_count', models.BigIntegerField(default=0)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.moderator')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_maker.subject')),
            ],
        ),
    ]
