# Generated by Django 4.2.1 on 2024-01-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0009_typetestupload_status'),
        ('moderator', '0005_checkedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedtest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_maker.subject'),
        ),
    ]
